// <auto-generated />
using System;
using BE_QuanLiDiem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE_QuanLiDiem.Migrations
{
    [DbContext(typeof(QL_DiemDbContext))]
    [Migration("20231213150303_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.BoMon", b =>
                {
                    b.Property<Guid>("MaBM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenBM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBM");

                    b.HasIndex("KhoaId");

                    b.ToTable("BoMons");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.DaiDoi", b =>
                {
                    b.Property<Guid>("MaDaiDoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhDaiDoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DaiDoiTruong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuanSo")
                        .HasColumnType("int");

                    b.Property<string>("TenDaiDoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDaiDoi");

                    b.ToTable("DaiDois");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.DayHoc", b =>
                {
                    b.Property<Guid>("MaDayHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GiangVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LopHocPhanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaDayHoc");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("LopHocPhanId");

                    b.ToTable("DayHocs");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.DiemTrungBinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("DTB")
                        .HasColumnType("real");

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<string>("HocVienId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TongTC")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HocVienId");

                    b.ToTable("DiemTrungBinhs");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.GiangVien", b =>
                {
                    b.Property<Guid>("MaGV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoMonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CapBac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("TenGV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGV");

                    b.HasIndex("BoMonId");

                    b.ToTable("GiangViens");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.HocPhan", b =>
                {
                    b.Property<Guid>("MaHocPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoMonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<int>("SoTC")
                        .HasColumnType("int");

                    b.Property<int>("SoTiet")
                        .HasColumnType("int");

                    b.Property<string>("TenHocPhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHocPhan");

                    b.HasIndex("BoMonId");

                    b.ToTable("HocPhans");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.HocTap", b =>
                {
                    b.Property<Guid>("MaHocTap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LopChuyenNganhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LopHocPhanId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaHocTap");

                    b.HasIndex("LopChuyenNganhId");

                    b.HasIndex("LopHocPhanId");

                    b.ToTable("HocTaps");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.HocVien", b =>
                {
                    b.Property<string>("MaHV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnhHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapBac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<Guid>("LopChuyenNganhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NgaySinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHV");

                    b.HasIndex("LopChuyenNganhId");

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.Khoa", b =>
                {
                    b.Property<Guid>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoas");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.LopChuyenNganh", b =>
                {
                    b.Property<Guid>("MaLopChuyenNganh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnhLCN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DaiDoiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoHV")
                        .HasColumnType("int");

                    b.Property<string>("TenLopChuyenNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLopChuyenNganh");

                    b.HasIndex("DaiDoiId");

                    b.ToTable("LopChuyenNganhs");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.LopHocPhan", b =>
                {
                    b.Property<string>("MaLopHocPhan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HocPhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoHV")
                        .HasColumnType("int");

                    b.HasKey("MaLopHocPhan");

                    b.HasIndex("HocPhanId");

                    b.ToTable("LopHocPhans");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.PhieuDiem", b =>
                {
                    b.Property<Guid>("MaPhieuDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("DiemCC")
                        .HasColumnType("real");

                    b.Property<float>("DiemTBM")
                        .HasColumnType("real");

                    b.Property<float>("DiemTX")
                        .HasColumnType("real");

                    b.Property<float>("DiemThi")
                        .HasColumnType("real");

                    b.Property<float>("DiemThiLai")
                        .HasColumnType("real");

                    b.Property<Guid>("HocPhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HocVienId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LanThi")
                        .HasColumnType("int");

                    b.HasKey("MaPhieuDiem");

                    b.HasIndex("HocPhanId");

                    b.HasIndex("HocVienId");

                    b.ToTable("PhieuDiems");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.tbl_RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("RefreshToken");

                    b.Property<string>("TokenId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TokenId");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("tbl_RefreshToken");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.tbl_user", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Code");

                    b.Property<Guid?>("MaDaiDoi")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MaDaiDoi");

                    b.Property<string>("MaHV")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MaHV");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Password");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Role");

                    b.HasKey("Id");

                    b.ToTable("tbl_user");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.BoMon", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.DayHoc", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .IsRequired();

                    b.HasOne("BE_QuanLiDiem.Models.Domain.LopHocPhan", "LopHocPhan")
                        .WithMany()
                        .HasForeignKey("LopHocPhanId")
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("LopHocPhan");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.DiemTrungBinh", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.HocVien", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.GiangVien", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.BoMon", "BoMon")
                        .WithMany()
                        .HasForeignKey("BoMonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoMon");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.HocPhan", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.BoMon", "BoMon")
                        .WithMany()
                        .HasForeignKey("BoMonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoMon");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.HocTap", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.LopChuyenNganh", "LopChuyenNganh")
                        .WithMany()
                        .HasForeignKey("LopChuyenNganhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_QuanLiDiem.Models.Domain.LopHocPhan", "LopHocPhan")
                        .WithMany()
                        .HasForeignKey("LopHocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopChuyenNganh");

                    b.Navigation("LopHocPhan");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.HocVien", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.LopChuyenNganh", "LopChuyenNganh")
                        .WithMany()
                        .HasForeignKey("LopChuyenNganhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopChuyenNganh");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.LopChuyenNganh", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.DaiDoi", "DaiDoi")
                        .WithMany()
                        .HasForeignKey("DaiDoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaiDoi");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.LopHocPhan", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.HocPhan", "HocPhan")
                        .WithMany()
                        .HasForeignKey("HocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocPhan");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.PhieuDiem", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.HocPhan", "HocPhan")
                        .WithMany()
                        .HasForeignKey("HocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_QuanLiDiem.Models.Domain.HocVien", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocPhan");

                    b.Navigation("HocVien");
                });
#pragma warning restore 612, 618
        }
    }
}
