// <auto-generated />
using System;
using BE_QuanLiDiem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE_QuanLiDiem.Migrations
{
    [DbContext(typeof(QL_DiemDbContext))]
    [Migration("20231027020822_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.BoMon", b =>
                {
                    b.Property<Guid>("MaBM")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhoaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenBM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBM");

                    b.HasIndex("KhoaId");

                    b.ToTable("BoMons");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.DaiDoi", b =>
                {
                    b.Property<Guid>("MaDaiDoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenDaiDoi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDaiDoi");

                    b.ToTable("DaiDois");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.DayHoc", b =>
                {
                    b.Property<Guid>("MaDayHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GiangVienId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LopHocPhanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MaDayHoc");

                    b.HasIndex("GiangVienId");

                    b.HasIndex("LopHocPhanId");

                    b.ToTable("DayHocs");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.GiangVien", b =>
                {
                    b.Property<Guid>("MaGV")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoMonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenGV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaGV");

                    b.HasIndex("BoMonId");

                    b.ToTable("GiangViens");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.HocPhan", b =>
                {
                    b.Property<Guid>("MaHocPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoMonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<int>("SoTC")
                        .HasColumnType("int");

                    b.Property<int>("SoTiet")
                        .HasColumnType("int");

                    b.Property<string>("TenHocPhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHocPhan");

                    b.HasIndex("BoMonId");

                    b.ToTable("HocPhans");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.HocVien", b =>
                {
                    b.Property<string>("MaHV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnhHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CapBac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<Guid>("LopChuyenNganhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenHV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHV");

                    b.HasIndex("LopChuyenNganhId");

                    b.ToTable("HocViens");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.Khoa", b =>
                {
                    b.Property<Guid>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoas");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.LopChuyenNganh", b =>
                {
                    b.Property<Guid>("MaLopChuyenNganh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DaiDoiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoHV")
                        .HasColumnType("int");

                    b.Property<string>("TenLopChuyenNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLopChuyenNganh");

                    b.HasIndex("DaiDoiId");

                    b.ToTable("LopChuyenNganhs");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.LopHocPhan", b =>
                {
                    b.Property<Guid>("MaLopHocPhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HocPhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoHV")
                        .HasColumnType("int");

                    b.HasKey("MaLopHocPhan");

                    b.HasIndex("HocPhanId");

                    b.ToTable("LopHocPhans");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.PhieuDiem", b =>
                {
                    b.Property<Guid>("MaPhieuDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("DiemCC")
                        .HasColumnType("real");

                    b.Property<float>("DiemTX")
                        .HasColumnType("real");

                    b.Property<float>("DiemThi")
                        .HasColumnType("real");

                    b.Property<float>("DiemThiLai")
                        .HasColumnType("real");

                    b.Property<string>("HocVienId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LanThi")
                        .HasColumnType("int");

                    b.Property<Guid>("LopHocPhanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MaPhieuDiem");

                    b.HasIndex("HocVienId");

                    b.HasIndex("LopHocPhanId");

                    b.ToTable("PhieuDiems");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.BoMon", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.Khoa", "Khoa")
                        .WithMany()
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.DayHoc", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.GiangVien", "GiangVien")
                        .WithMany()
                        .HasForeignKey("GiangVienId")
                        .IsRequired();

                    b.HasOne("BE_QuanLiDiem.Models.Domain.LopHocPhan", "LopHocPhan")
                        .WithMany()
                        .HasForeignKey("LopHocPhanId")
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("LopHocPhan");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.GiangVien", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.BoMon", "BoMon")
                        .WithMany()
                        .HasForeignKey("BoMonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoMon");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.HocPhan", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.BoMon", "BoMon")
                        .WithMany()
                        .HasForeignKey("BoMonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoMon");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.HocVien", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.LopChuyenNganh", "LopChuyenNganh")
                        .WithMany()
                        .HasForeignKey("LopChuyenNganhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopChuyenNganh");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.LopChuyenNganh", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.DaiDoi", "DaiDoi")
                        .WithMany()
                        .HasForeignKey("DaiDoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DaiDoi");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.LopHocPhan", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.HocPhan", "HocPhan")
                        .WithMany()
                        .HasForeignKey("HocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocPhan");
                });

            modelBuilder.Entity("BE_QuanLiDiem.Models.Domain.PhieuDiem", b =>
                {
                    b.HasOne("BE_QuanLiDiem.Models.Domain.HocVien", "HocVien")
                        .WithMany()
                        .HasForeignKey("HocVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_QuanLiDiem.Models.Domain.LopHocPhan", "LopHocPhan")
                        .WithMany()
                        .HasForeignKey("LopHocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HocVien");

                    b.Navigation("LopHocPhan");
                });
#pragma warning restore 612, 618
        }
    }
}
